version: "3.0"

services:
  shiny:
    container_name: shiny
    image: redditorapp
    restart: always
    user: 'root'
    # Uncomment the lines below to disable application logs STDOUT output
    # environment:
    #   - APPLICATION_LOGS_TO_STDOUT=false
    ports:
      - '3000:3838'
    volumes:
      - './shiny-server.conf:/etc/shiny-server/shiny-server.conf'
      - './app.R:/app/app.R'
      - './.env:/app/.Renviron'
