version: '3.4'
services:
  redditapione:      
    image: redditorapi
    command: /app/plumber.R
    restart: always
    ports:
     - "8000:8000"
    working_dir: /app
    volumes:
      - ./.env:/app/.Renviron
      - ./plumber.R:/app/plumber.R
  redditapitwo:
    image: redditorapi
    command: /app/plumber.R
    restart: always
    ports:
     - "8001:8000"
    working_dir: /app
    volumes:
      - ./.env:/app/.Renviron
      - ./plumber.R:/app/plumber.R
  redditapithree:
    image: redditorapi
    command: /app/plumber.R
    restart: always
    ports:
     - "8002:8000"
    working_dir: /app
    volumes:
      - ./.env:/app/.Renviron
      - ./plumber.R:/app/plumber.R
  redditapifour:
    image: redditorapi
    command: /app/plumber.R
    restart: always
    ports:
     - "8003:8000"
    working_dir: /app
    volumes:
      - ./.env:/app/.Renviron
      - ./plumber.R:/app/plumber.R
  redditapifive:
    image: redditorapi
    command: /app/plumber.R
    restart: always
    ports:
     - "8004:8000"
    working_dir: /app
    volumes:
      - ./.env:/app/.Renviron
      - ./plumber.R:/app/plumber.R
